require './brewfiles/m1_utils.rb'

brew "zsh-completion"
brew "zsh-syntax-highlighting"
brew "tmux"
brew "rsync"
brew "git"
brew "wget"
brew "curl"
brew "tree"
brew "nkf"
brew "jq"
brew "pigz"
brew "grep"
brew "lnav"
brew "diff-pdf"

#brew "awscli"   # moved to aqua.yaml
#brew "azure-cli"
cask "gcloud-cli"

#brew "saml2aws"   # moved to aqua.yaml

brew "mysql-client@8.0"
brew "postgresql@17"

brew "anyenv"
brew "n"
brew "pipx"
brew "pnpm"

brew "ffmpeg"
brew "pv"
brew "mas"
brew "mkcert"
brew "nss" 

tap "mackerelio/mackerel-agent", trusted: true
brew "mackerelio/mackerel-agent/mkr", trusted: true

tap "olets/tap", trusted: true
brew "olets/tap/zsh-abbr", trusted: true

#tap "cloudflare/cloudflare", trusted: true
#cask "cloudflare/cloudflare/cf-terraforming", trusted: true    # needs GRANT security & privacy

tap "ynqa/tap", trusted: true
brew "ynqa/tap/jnv", trusted: true

brew "deno"

#cask "1password-cli"   # moved to aqua.yaml

brew "gonzo"
brew "pwgen"
brew "ni"

brew "jc"     # move from aqua.yaml 
brew "dasel"  # move from aqua.yaml 

brew "webp"

tap "kreuzwerker/taps", trusted: true
tap "aquaproj/aqua", trusted: true
